# Generated by Django 5.1 on 2024-08-19 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('chats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history_set', to='chat.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_set', to='chat.chathistory'),
        ),
    ]
