# Generated by Django 5.1 on 2024-08-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_uploadedfile_alter_chathistory_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='chats',
        ),
    ]
