# Generated by Django 5.1 on 2024-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chathistory_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='text_content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
